### ISSUE TITLE
WDS - trainer presentation - corrections needed

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Intelligent-vending-machines#3]
1-Correct naming convention please:  WDS trainer presentation - Intelligent vending machines

2-Abstract on the PPT is the workshop abstract, not the WDS abstract on the ReadMe page.

3-Alt-text is written twice for each image?
Picture of question mark

Picture of a question mark icon.

**Comment by kylebunting** [comment]
Updates made. 

The alt-text appearing twice was because we had to go through before and add both titles and alt-text. Now it appears that adding a title in no longer an option, so I updated to just display the alt-text.
