### ISSUE TITLE
Document headers/title section

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Intelligent-vending-machines#6]
Please update document title pages to match templates (remove Updated xxx further down if you added it there please).

<div class="MCWHeader1">
[Insert workshop name here]
</div>

<div class="MCWHeader2">
Whiteboard design session trainer guide
</div>

<div class="MCWHeader3">
[Insert date here Month Year]
</div>

**Comment by kylebunting** [comment]
Added to all HOL and WDS documents.
