### ISSUE TITLE
Before the HOL document

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Intelligent-vending-machines#8]
Please add header, titles & TOC from template.
Document needs to be renamed to remove dashes (check for links that may change)

FYI - MS Style guide says bulleted and/or numbered instructions to not have a period at the end unless they are multiple sentences.  We're leaving in questions marks and colons.  I've corrected them in this document but you might want to look through for future reference.  Thanks! DD

**Comment by kylebunting** [comment]
Header, titles, and TOC added based on template.
